//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings_380_jh : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings_380_jh defaultInstance_380_jh = ((Settings_380_jh)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_380_jh())));

        public static Settings_380_jh Default_380_jh
        {
            get
            {
                return defaultInstance_380_jh;
            }
        }
    }
}
